/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as FrotaRouteImport } from './routes/frota'
import { Route as DiariaMensalRouteImport } from './routes/diaria-mensal'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AplicativoRouteImport } from './routes/aplicativo'
import { Route as Adm_loginRouteImport } from './routes/adm_login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrosIdRouteImport } from './routes/carros.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminPropostasRouteImport } from './routes/_authenticated/admin.propostas'
import { Route as AuthenticatedAdminCidadesRouteImport } from './routes/_authenticated/admin.cidades'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaRoute = FrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => rootRouteImport,
} as any)
const DiariaMensalRoute = DiariaMensalRouteImport.update({
  id: '/diaria-mensal',
  path: '/diaria-mensal',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicativoRoute = AplicativoRouteImport.update({
  id: '/aplicativo',
  path: '/aplicativo',
  getParentRoute: () => rootRouteImport,
} as any)
const Adm_loginRoute = Adm_loginRouteImport.update({
  id: '/adm_login',
  path: '/adm_login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosIdRoute = CarrosIdRouteImport.update({
  id: '/carros/$id',
  path: '/carros/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPropostasRoute =
  AuthenticatedAdminPropostasRouteImport.update({
    id: '/propostas',
    path: '/propostas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCidadesRoute =
  AuthenticatedAdminCidadesRouteImport.update({
    id: '/cidades',
    path: '/cidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm_login': typeof Adm_loginRoute
  '/aplicativo': typeof AplicativoRoute
  '/assinatura': typeof AssinaturaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/diaria-mensal': typeof DiariaMensalRoute
  '/frota': typeof FrotaRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/carros/$id': typeof CarrosIdRoute
  '/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/admin/propostas': typeof AuthenticatedAdminPropostasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adm_login': typeof Adm_loginRoute
  '/aplicativo': typeof AplicativoRoute
  '/assinatura': typeof AssinaturaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/diaria-mensal': typeof DiariaMensalRoute
  '/frota': typeof FrotaRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/carros/$id': typeof CarrosIdRoute
  '/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/admin/propostas': typeof AuthenticatedAdminPropostasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adm_login': typeof Adm_loginRoute
  '/aplicativo': typeof AplicativoRoute
  '/assinatura': typeof AssinaturaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/diaria-mensal': typeof DiariaMensalRoute
  '/frota': typeof FrotaRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/carros/$id': typeof CarrosIdRoute
  '/_authenticated/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/_authenticated/admin/propostas': typeof AuthenticatedAdminPropostasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm_login'
    | '/aplicativo'
    | '/assinatura'
    | '/como-funciona'
    | '/diaria-mensal'
    | '/frota'
    | '/sobre'
    | '/admin'
    | '/carros/$id'
    | '/admin/cidades'
    | '/admin/propostas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adm_login'
    | '/aplicativo'
    | '/assinatura'
    | '/como-funciona'
    | '/diaria-mensal'
    | '/frota'
    | '/sobre'
    | '/admin'
    | '/carros/$id'
    | '/admin/cidades'
    | '/admin/propostas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/adm_login'
    | '/aplicativo'
    | '/assinatura'
    | '/como-funciona'
    | '/diaria-mensal'
    | '/frota'
    | '/sobre'
    | '/_authenticated/admin'
    | '/carros/$id'
    | '/_authenticated/admin/cidades'
    | '/_authenticated/admin/propostas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  Adm_loginRoute: typeof Adm_loginRoute
  AplicativoRoute: typeof AplicativoRoute
  AssinaturaRoute: typeof AssinaturaRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  DiariaMensalRoute: typeof DiariaMensalRoute
  FrotaRoute: typeof FrotaRoute
  SobreRoute: typeof SobreRoute
  CarrosIdRoute: typeof CarrosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota': {
      id: '/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof FrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaria-mensal': {
      id: '/diaria-mensal'
      path: '/diaria-mensal'
      fullPath: '/diaria-mensal'
      preLoaderRoute: typeof DiariaMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplicativo': {
      id: '/aplicativo'
      path: '/aplicativo'
      fullPath: '/aplicativo'
      preLoaderRoute: typeof AplicativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm_login': {
      id: '/adm_login'
      path: '/adm_login'
      fullPath: '/adm_login'
      preLoaderRoute: typeof Adm_loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carros/$id': {
      id: '/carros/$id'
      path: '/carros/$id'
      fullPath: '/carros/$id'
      preLoaderRoute: typeof CarrosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/propostas': {
      id: '/_authenticated/admin/propostas'
      path: '/propostas'
      fullPath: '/admin/propostas'
      preLoaderRoute: typeof AuthenticatedAdminPropostasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cidades': {
      id: '/_authenticated/admin/cidades'
      path: '/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AuthenticatedAdminCidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCidadesRoute: typeof AuthenticatedAdminCidadesRoute
  AuthenticatedAdminPropostasRoute: typeof AuthenticatedAdminPropostasRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCidadesRoute: AuthenticatedAdminCidadesRoute,
  AuthenticatedAdminPropostasRoute: AuthenticatedAdminPropostasRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  Adm_loginRoute: Adm_loginRoute,
  AplicativoRoute: AplicativoRoute,
  AssinaturaRoute: AssinaturaRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  DiariaMensalRoute: DiariaMensalRoute,
  FrotaRoute: FrotaRoute,
  SobreRoute: SobreRoute,
  CarrosIdRoute: CarrosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
