/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MensalRouteImport } from './routes/mensal'
import { Route as FrotaRouteImport } from './routes/frota'
import { Route as DiariaRouteImport } from './routes/diaria'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AplicativoRouteImport } from './routes/aplicativo'
import { Route as Adm_loginRouteImport } from './routes/adm_login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrosIdRouteImport } from './routes/carros.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminPropostasRouteImport } from './routes/_authenticated/admin_.propostas'
import { Route as AuthenticatedAdminCidadesRouteImport } from './routes/_authenticated/admin_.cidades'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MensalRoute = MensalRouteImport.update({
  id: '/mensal',
  path: '/mensal',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaRoute = FrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => rootRouteImport,
} as any)
const DiariaRoute = DiariaRouteImport.update({
  id: '/diaria',
  path: '/diaria',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicativoRoute = AplicativoRouteImport.update({
  id: '/aplicativo',
  path: '/aplicativo',
  getParentRoute: () => rootRouteImport,
} as any)
const Adm_loginRoute = Adm_loginRouteImport.update({
  id: '/adm_login',
  path: '/adm_login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosIdRoute = CarrosIdRouteImport.update({
  id: '/carros/$id',
  path: '/carros/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPropostasRoute =
  AuthenticatedAdminPropostasRouteImport.update({
    id: '/admin_/propostas',
    path: '/admin/propostas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCidadesRoute =
  AuthenticatedAdminCidadesRouteImport.update({
    id: '/admin_/cidades',
    path: '/admin/cidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm_login': typeof Adm_loginRoute
  '/aplicativo': typeof AplicativoRoute
  '/assinatura': typeof AssinaturaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/diaria': typeof DiariaRoute
  '/frota': typeof FrotaRoute
  '/mensal': typeof MensalRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carros/$id': typeof CarrosIdRoute
  '/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/admin/propostas': typeof AuthenticatedAdminPropostasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adm_login': typeof Adm_loginRoute
  '/aplicativo': typeof AplicativoRoute
  '/assinatura': typeof AssinaturaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/diaria': typeof DiariaRoute
  '/frota': typeof FrotaRoute
  '/mensal': typeof MensalRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carros/$id': typeof CarrosIdRoute
  '/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/admin/propostas': typeof AuthenticatedAdminPropostasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adm_login': typeof Adm_loginRoute
  '/aplicativo': typeof AplicativoRoute
  '/assinatura': typeof AssinaturaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/diaria': typeof DiariaRoute
  '/frota': typeof FrotaRoute
  '/mensal': typeof MensalRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/carros/$id': typeof CarrosIdRoute
  '/_authenticated/admin_/cidades': typeof AuthenticatedAdminCidadesRoute
  '/_authenticated/admin_/propostas': typeof AuthenticatedAdminPropostasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm_login'
    | '/aplicativo'
    | '/assinatura'
    | '/como-funciona'
    | '/diaria'
    | '/frota'
    | '/mensal'
    | '/sobre'
    | '/admin'
    | '/carros/$id'
    | '/admin/cidades'
    | '/admin/propostas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adm_login'
    | '/aplicativo'
    | '/assinatura'
    | '/como-funciona'
    | '/diaria'
    | '/frota'
    | '/mensal'
    | '/sobre'
    | '/admin'
    | '/carros/$id'
    | '/admin/cidades'
    | '/admin/propostas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/adm_login'
    | '/aplicativo'
    | '/assinatura'
    | '/como-funciona'
    | '/diaria'
    | '/frota'
    | '/mensal'
    | '/sobre'
    | '/_authenticated/admin'
    | '/carros/$id'
    | '/_authenticated/admin_/cidades'
    | '/_authenticated/admin_/propostas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  Adm_loginRoute: typeof Adm_loginRoute
  AplicativoRoute: typeof AplicativoRoute
  AssinaturaRoute: typeof AssinaturaRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  DiariaRoute: typeof DiariaRoute
  FrotaRoute: typeof FrotaRoute
  MensalRoute: typeof MensalRoute
  SobreRoute: typeof SobreRoute
  CarrosIdRoute: typeof CarrosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensal': {
      id: '/mensal'
      path: '/mensal'
      fullPath: '/mensal'
      preLoaderRoute: typeof MensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota': {
      id: '/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof FrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaria': {
      id: '/diaria'
      path: '/diaria'
      fullPath: '/diaria'
      preLoaderRoute: typeof DiariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplicativo': {
      id: '/aplicativo'
      path: '/aplicativo'
      fullPath: '/aplicativo'
      preLoaderRoute: typeof AplicativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm_login': {
      id: '/adm_login'
      path: '/adm_login'
      fullPath: '/adm_login'
      preLoaderRoute: typeof Adm_loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carros/$id': {
      id: '/carros/$id'
      path: '/carros/$id'
      fullPath: '/carros/$id'
      preLoaderRoute: typeof CarrosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/propostas': {
      id: '/_authenticated/admin_/propostas'
      path: '/admin/propostas'
      fullPath: '/admin/propostas'
      preLoaderRoute: typeof AuthenticatedAdminPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/cidades': {
      id: '/_authenticated/admin_/cidades'
      path: '/admin/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AuthenticatedAdminCidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminCidadesRoute: typeof AuthenticatedAdminCidadesRoute
  AuthenticatedAdminPropostasRoute: typeof AuthenticatedAdminPropostasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminCidadesRoute: AuthenticatedAdminCidadesRoute,
  AuthenticatedAdminPropostasRoute: AuthenticatedAdminPropostasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  Adm_loginRoute: Adm_loginRoute,
  AplicativoRoute: AplicativoRoute,
  AssinaturaRoute: AssinaturaRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  DiariaRoute: DiariaRoute,
  FrotaRoute: FrotaRoute,
  MensalRoute: MensalRoute,
  SobreRoute: SobreRoute,
  CarrosIdRoute: CarrosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
